version: "3.9"
services:
  mlflow:
    image: mlflow/mlflow
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns -h 0.0.0.0
    ports: ["5000:5000"]
  app:
    build: .
    volumes: ["./data:/app/data"]
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
